name: extensioneer
version: '0.1.0.0'
category: CLI
author: Markus Läll
maintainer: markus.l2ll@gmail.com
license: MIT
license-file: LICENSE
extra-source-files:
- CHANGELOG.md

synopsis: Inspect extensions in cabal and hpack files
description: |

  extensioneer - Inspect extensions in cabal and hpack files

  See readme for more: https://github.com/eyeinsky/extensioneer


dependencies:
- Cabal
- base >= 4.11 && < 5
- containers
- directory
- hpack
- mtl
- optparse-applicative
- yaml

executable:
  main: Main.hs
  source-dirs: src

default-extensions:
- Arrows
- BangPatterns
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFunctor
- DeriveGeneric
- DerivingStrategies
- DerivingVia
- EmptyDataDecls
- ExtendedDefaultRules
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- ImportQualifiedPost
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- NamedFieldPuns
- NoImplicitPrelude
- NoMonomorphismRestriction
- OverloadedStrings
- PolyKinds
- QuasiQuotes
- RankNTypes
- RecordWildCards
- RecursiveDo
- ScopedTypeVariables
- StandaloneDeriving
- StandaloneKindSignatures
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- TypeInType
- TypeOperators
- TypeSynonymInstances
- UndecidableInstances
